name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'   # publish only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload settings.xml for debugging
        uses: actions/upload-artifact@v4
        with:
          name: maven-settings
          path: .github/maven/settings.xml
      - name: Build and Publish
        run: |
          mvn -B package
          mvn -B deploy
